### ISSUE TITLE
Функции библиотеки poppler

### ISSUE THREAD

**Issue by acanna** [acanna/biblio#4]

**Comment by evlinsky** [comment]
1. умеет ли вообще библиотека работать со статьями из картинок
2. можно ли выдрать только одну страницу
3. можно ли выдрать часть страницы
4. можно ли обращаться к отдельным пикселям на странице, чтобы определить, какую часть выдирать
5. можно ли сохранить страницу в виде картинки
6. можно ли определить какого вида статья: с текстом или в виде картинки

**Comment by evlinsky** [comment]
7. Можно ли узнать размер шрифта и выравнивание:
- title шрифт 20, выравнивание центральное
- authors шрифт 10, выравнивание центральное

**Comment by acanna** [comment]
Wiki по библиотеке: http://marpirk.github.io/poppler-cpp-doc/index.html
