### ISSUE TITLE
Многопоточность

### ISSUE THREAD

**Issue by evlinsky** [acanna/biblio#44]
1. Заменить отдельные переменные 
thread t1;
thread t2;
thread t3;
на  vector<thread> threads.

2. Сделать функцию подсчета расстояния параметром главной функции (использовать указатели на функцию)

**Comment by acanna** [comment]
количество тредов как параметр

**Comment by acanna** [comment]
terminate called after throwing an instance of 'Biblio_exception'
  what():  CURL initialization failed

**Comment by acanna** [comment]
передаем вектор указателей, потому потоки работают с одним адресом
передавать только данные для инициализации?
