### ISSUE TITLE
Улучшить вывод в html

### ISSUE THREAD

**Issue by evlinsky** [acanna/biblio#48]
1. Оформление:
Donald E. Knuth:
Selected Papers on Fun and Games. CSLI lecture notes series 192, Cambridge University Press 2011, ISBN 978-1-57586-584-3, pp. I-XVII, 1-741

2. Название должно являться ссылкой (<a href >) на pdf на локальном диске

**Comment by acanna** [comment]
Оформление сделано такое:

Hyunwoo Nam, Kyung-Hwa Kim, Jong-Yul Kim, Henning Schulzrinne:
Towards QoE-aware video streaming using SDN. Conference and Workshop Papers. GLOBECOM. 2014. 1317-1322.
http://dblp.org/rec/conf/globecom/NamKKS14
