### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by YanaVKuznetsova** [acanna/biblio#54]

**Comment by evlinsky** [comment]
Есть еще альтернативный подход libconfig (не json и не xml). Работает из коробки (не надо свой код поверх чтения файлов писать).  Есть C и C++ интерфейсы:
http://jpmens.net/2009/09/17/reading-configuration-files-with-libconfig/
http://emocias.blogspot.ru/2011/06/libconfig-cc-configuration-file-library.html

Рекомендую =)
